import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import FluentUIProvider from "./Components/Providers/FluentUIProvider";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cuernatours",
  description: "Generated by MonkeyBusiness",
  icons: {
    icon: "/Images/CuernaToursAsset3.svg",
    shortcut: "/Images/CuernaToursAsset3.svg",
    apple: "/Images/CuernaToursAsset3.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <FluentUIProvider>
          {children}
        </FluentUIProvider>
      </body>
    </html>
  );
}
