import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FluentUIProvider from "./Components/Providers/FluentUIProvider";
import PageTransition from "./Components/PageTransition/PageTransition";
import { AuthProvider } from "./Contexts/AuthContext/AuthContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cuernatours",
  description: "Generated by MonkeyBusiness",
  icons: {
    icon: "/Images/CuernaToursAsset3.svg",
    shortcut: "/Images/CuernaToursAsset3.svg",
    apple: "/Images/CuernaToursAsset3.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <FluentUIProvider>
          <AuthProvider>
            <PageTransition>
              {children}
            </PageTransition>
          </AuthProvider>
        </FluentUIProvider>
      </body>
    </html>
  );
}

